[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "mercuryFramework"
version = "0.0.1-b057"
dependencies = [
    "numpy",
    "pandas",
    "binance-connector",
    "dataclasses"
]